#!/bin/sh

git pull origin master
git submodule init 
git submodule update

# TODO
XDG_CONFIG_HOME=$HOME/.config
VIM_CONFIG=$(realpath $(dirname $0))
NVIM_CONFIG=$XDG_CONFIG_HOME/nvim
VIMRC=$HOME/.vimrc

echo
echo "NVIM_CONFIG=$NVIM_CONFIG"
echo "VIM_CONFIG=$VIM_CONFIG"
echo

ln -sf $VIM_CONFIG/vimrc $VIMRC
echo "$VIMRC => $(readlink $VIMRC)"

mkdir -p $XDG_CONFIG_HOME >/dev/null 2>&1
if  [[ ! -L $NVIM_CONFIG ]] || [ "$(readlink $NVIM_CONFIG)" != $VIM_CONFIG ] ; then
	if [[ -d $NVIM_CONFIG ]] ; then
		echo "NeoVim config $NVIM_CONFIG already exists. Remove it and re-run $0"
		exit 1
	else
		echo "Symlinking NeoVim config $NVIM_CONFIG => $VIM_CONFIG."
		ln -sf $VIM_CONFIG $NVIM_CONFIG
	fi
fi

echo "$NVIM_CONFIG => $(readlink $NVIM_CONFIG)"

echo
